name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */5 * * *'  # 每 5 小时执行一次，UTC 时间
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史，避免 rebase 问题

      - name: Configure Git
        run: |
          git config --global user.name "streamlit-bot"
          git config --global user.email "bot@example.com"

      - name: Update keepalive log
        run: echo "Keepalive ping: $(date -u)" >> keepalive.log

      - name: Commit, pull --rebase and push if changed
        run: |
          git add keepalive.log
          if ! git diff --cached --quiet; then
            git commit -m "keepalive update $(date -u)"
            git pull --rebase origin main
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
        env:
          GIT_ASKPASS: /bin/echo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
